language: dart
dart:
  - stable
  - beta
  - "2.10.3"
  - "2.9.3"
  - "2.8.4"
  - "2.7.2"
before_install:
  - sudo apt-get -y install libc6
script:
  - pub get
  - pub run test
  - pub run codecov --report-on=bin/ --no-html --verbose test/env_test.dart
  - bash <(curl -s https://codecov.io/bash)
