language: dart
dart:
  - stable
before_install:
  - sudo apt-get -y install glibc
script:
  - pub get --packages-dir
  - pub run test
  - pub run dart_codecov_generator --report-on=bin/ --no-html --verbose test/env_test.dart
  - bash <(curl -s https://codecov.io/bash)
