name: dart_codecov_generator
version: 0.4.0
description: Generates lcov and/or HTML coverage reports for Dart projects. (UNIX only)
authors:
  - John Ryan <john.p.ryan4@gmail.com>
  - Evan Weible <ekweible@gmail.com>
homepage: https://github.com/codecov/dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.5.1
  logging: ^0.11.3+2
dev_dependencies:
  coverage: ^0.12.4
  test: ^1.5.3
executables:
  dart_codecov_generator:
  generate_coverage:
